---
title: "R-Parte1"
author: "Daniel Enriquez"
date: "2023-12-28"
output: ioslides_presentation
---
## **Directorio de Trabajo** ~*(wd, working directory)*~

* Dirección o ubicación (carpeta o folder) para importar/exportar/cargar/guardar archivos.
* Tip: *Evitar espacios, tildes o carácteres en el nombre.*

* Comandos útiles:
  * `getwd()`: Cuál es la dirección actual?
  * `setwd()`: Definir la dirección
  * `dir()`: Generar una lista de archivos y carpetas en el *wd*.
  + `ls()`: Genera una lista de objetos abiertos en R.

## **Ejemplo N1**

Los comentarios dentro del código son incluidos con `#`.

```{r}
#Ejemplo en MacOS, en Windows "C:/Docum..")
setwd("/Users/denriquez/Documents/Rstats/RepoGit/R-estudiantes") 
#Comprobar el wd
getwd()  
#Lista de archivos en wd
dir()

```
## **Objetos**

Ojo: Cada `Función` trabaja con un tipo específico de Obj.  `getClassDef`
Tipos de Obj.:

  * **Vectores:** números, carácteres, fórmulas.
  
  * **Matrices:** varias columnas del mismo tipo y longitud.
  
  * ***Arrays:*** como Matrices pero con más dimensiones.
  
  * ***Data frames:*** clásica base de datos con columnas de diferentes tipos.
  
  * **Listas:** lista de objetos de diferente tipo.
  
  * **Factores:** Un vector con niveles.
  
  * **Obj. Avanzados:** S3, S4 (Listas con información interconectada).  Ejemplo: plots o información genética.

## **Operaciones básicas**
* Crear un vector (`<-` o `=`), concatenar  (`c()`) y mostrar resultados. *para valores repetidos: `rep`
```{R}
dev<-c(1,2,3,4,5,6,7,8,9,10)
dev
```
* Características del objeto: 
```{R, results='hold'}
length(dev) #longitud
str(dev) #resumen o estructura
```
* Otros: `class()`, `mode()`.

## **Operaciones básicas(II)**
Manipular un vector.
```{R, results='hold'}
dev[4] #Seleccionar el 4to elemento
dev[5:8] #Seleccionar del 5to al 8vo elemento.
dev2<-dev[-6] #Eliminar el 6to elemento
dev2 #Mostrar el resultado de la operación anterior
```
## **Operaciones básicas(III)**
Crear una matriz.
```{R, results='hold'}
dev.m<-matrix(data=11:20, nrow=2, ncol=5) #2 filas y 5 columnas
is.matrix(dev.m) # es dev.m una matriz?
dev.m #Mostrar la matriz
dim(dev.m) #dimensiones. (2 x 5)
dev.m[,3] #Mostrar la 3ra columna
dev.m[2,] #Mostrar la 2da fila
dev.m[2,3] #Mostrar un elemento con las coordenadas
```
## **Operaciones básicas(IV)**
Manipular una matriz.
```{R, results='hold'}
dev.m[,2:4] #Mostrar valores de las columnas 2 a 4
dev1<-c(dev, dev.m[2,]) #concatenar el vector dev a la fila 2.
dev1
dev1<-c(dev.m[1,]) #reemplazar vector por la fila 1
dev1
rm(dev1) #elimina dev1
dev1<-rep(x=10, each=5) #5 repeticiones del valor 10
dev1[dev1==10]<-"diez" #Operacion logica
dev1
```

## **Operaciones básicas(V)**
```{R, results='hold'}
summary(dev.m) #Estadísticas básicas
```
## **Operaciones básicas(VI)**
```{R, results='hold'}
colnames(dev.m)<-c("A", "B", "C", "D", "E") #Renombrar columnas
dev.m
dev.m[,c("C","E")] #Extraer dos columnas por su nombre
t(dev.m) #Transponer elementos

```
## **Operaciones básicas(VII)**
```{R, results='hold'}
dev.m2<-matrix(rep(c(1:6)), nrow=6, ncol=6)
diag(dev.m2) #diagonal de la matrix
diag(dev.m2)<-rep(x=c(1,2), times=3)
dev.m2
```

## **Bases de Datos ** ~*(DF, data frame)*~
```{R, results='hold'}
#¿Qué tipo de variable tenemos?
#rm(list=ls()) #limpiar el entorno
dev.m2<-matrix(rep(c(1:6)), nrow=6, ncol=6)
is.matrix(dev.m2)
class(dev.m2)
#Conversión a DF
dev.df<-as.data.frame(dev.m2)
class(dev.df)

```
